- src/zimscraperlib/fix_ogvjs_dist.py
This makes the fix_ogvjs_dist.py more generic by adding functionality as mentioned in issue #1 .
@rgaudin @kelson42 please suggest changes/improvements.
Fixes #1
> Make paths more generic

- CHANGELOG.md
- src/zimscraperlib/zim.py
- tests/zim/test_zim.py
Fixes #20 by making make_zim_file() take in kwargs which are passed to to_zimwriterfs_args(). Also, made it take the zimwriterfs binary location from the object of ZimInfo that's passed as it would allow to change it easily if required. Also added some docstrings regarding the arguments.
This one changes the API
> Support for all arguments in make_zim_file()

- CHANGELOG.md
- src/zimscraperlib/imaging.py
- tests/imaging/test_imaging.py
Contains the following changes -
- added argument allow_upscaling to upscale image if it cannot be resized due to smaller dimentions than required
- use src instead of png_image in tests
- use _ for unused variables in tests
- add tests for allow_upscaling
- convert image to RGB if saving as JPEG
Also, this would fix https://github.com/openzim/youtube/issues/104
This is compatible with the previous API but contains an extra option allow_upscaling
> Better image resizing

- CHANGELOG.md
- src/zimscraperlib/zim/rewriting.py
- tests/zim/conftest.py
- tests/zim/test_rewriting.py
- tests/zim/test_zim_creator.py
This prevents KeyError while rewriting links if the HTML tag doesn't contain the attribute holding the link. For example, <a> tags without href are still valid.
Also adds object element link rewriting if data attribute contains a link.
> Fix zim url rewritting on node without expected attribute

- CHANGELOG.md
- src/zimscraperlib/zim/rewriting.py
- tests/zim/conftest.py
- tests/zim/test_rewriting.py
This fixes the following -
- ~~Proper rewriting of root-relative links~~ - Dropped as its forbidden in ZIM and shall be handled by scrapers given that we plan to get rid of namespaces
- CSS URLs are now found in a non greedy manner
Additional changes -
- Changed str to Path in test_fix_target_for() as the function it tests expects a Path
> Fix HTML link rewriting and CSS link rewriting

- CHANGELOG.md
- src/zimscraperlib/zim/filesystem.py
This fixes #38 by using mimetypes guessed from filenames for the files reported as text (and not just text/plain) by magic.
> Use mimetypes guessed from filenames for text files

- src/zimscraperlib/zim/rewriting.py
- tests/zim/test_rewriting.py
This fixes #35 by implementing the following two functions in `zimscraperlib.zim.rewriting` -
- `find_language_in()` - Finds the language using the order mentioned in #35
- `find_language_in_file()` - Finds the language using `find_language_in()` from a file
Tests are also implemented for the same.
> Get language from HTML

- CHANGELOG.md
- src/zimscraperlib/zim/creator.py
When using StaticArticle without a filename (`content=`) get_data() should return
the passed content bytes.
This behavior is toggled based on the result of `get_filename()`.
Casting to `str` the filename argument resulted in get_filename() to return `"None"`
fooling it into thinking it's a filename based StaticArticle
> Fixed StaticArticle usage with content=

- CHANGELOG.md
- src/zimscraperlib/zim/rewriting.py
This allows rewriting of links in poster attribute of <audio> element used by videojs audio player. 
Unrelated - Added changelog for language extraction from HTML content and file as I didn't put it in that PR.
> Rewrite links from poster attribute of audio element when creating ZIMs

- CHANGELOG.md
- src/zimscraperlib/download.py
- src/zimscraperlib/imaging.py
- tests/imaging/test_imaging.py
Pillow automatically uses the destination filename extension to guess format when saving
an Image. It seems odd that we require the destination format separately.
With this, the format is now optionnal (as `fmt` arg). It is also normalized as Pillow
uses all-upercase formats.
`colorspace` argument is also moved to keyword arguments as its use is unlikely while
setting save parameters should be a lot more common.
> Better defaults for convert_image()

- CHANGELOG.md
- src/zimscraperlib/zim/rewriting.py
- tests/zim/conftest.py
This disables link rewriting for `mailto:` links and hence fixes #46.
> Do not rewrite mailto: links while creating ZIM

- CHANGELOG.md
- src/zimscraperlib/zim/rewriting.py
- tests/zim/test_rewriting.py
This fixes #53 by correctly rewriting of links with empty target. Also adds a test for the same.
> Fix rewriting of links with empty target

- tests/zim/test_fs.py
github CI py36 apparently catches -6 retcode for that failure test
> also expecting -6 retcode on test

- src/zimscraperlib/image/__init__.py
Import the Image module correctly from PIL instead of searching an attribute in an empty stub
> Prevent import errors while importing PIL.Image

- CHANGELOG.md
- requirements.txt
- src/zimscraperlib/download.py
- tests/download/test_download.py
This adds a `YoutubeDownloader` class in `download.py` to download youtube videos on a constant number of threads. It has a method called `download()` which allows it to work like a normal serial function that can be then parallelized in the scrapers. However, it downloads on its own executor, hence, the number of workers actually downloading the videos gets reduced to the limit that is set during initialization.
The YoutubeDownloader has the following members -
- `executor` - A ThreadPoolExecutor which is initialized with a limited number of threads
- `video_format` - same as what we use in the scrapers (both webm and mp4 supported)
The `YoutubeDownloader` has the following methods -
- `__init__()` - Used to initialize the `executor` and the `video_format` 
- `shutdown()` - Used to …
> Add YoutubeDownloader class in download.py

- CHANGELOG.md
- src/zimscraperlib/download.py
- tests/download/test_download.py
This fixes #61 by adding a `wait` parameter in `YoutubeDownloader.download()` which allows to disable waiting for the completion of the current job and return a `Future` object in that case. The usage in the tests is also fixed.
> Add wait parameter in YoutubeDownloader.download()

- CHANGELOG.md
- src/zimscraperlib/image/optimization.py
- tests/download/test_download.py
- tests/image/test_image.py
This fixes #64 by handling wrong extension while optimizing images. It creates a copy of the original file with correct extension if wrong extension is found. 
Also, unrelated - Use correct directory in the yt_downloader context manager test to not have files downloaded in workdir,
> Handle wrong extension in optimize_image()

- CHANGELOG.md
- src/zimscraperlib/video/presets.py
- tests/video/test_video.py
This adds two new presets for high quality WebM and Mp4 encoding. These are `VideoWebmHigh` and `VideoMp4High`. Both use constant quality mode using `-cbr` and it is set to a value where we get quality similar to the source and a similar filesize too, The lower the value of `-cbr`, the higher the quality and the higher the filesize.
> Add high quality presets for WebM and Mp4 encoding

- CHANGELOG.md
- src/zimscraperlib/download.py
- src/zimscraperlib/inputs.py
- tests/download/test_download.py
This replaces save_file() with stream_file() which will allow streaming to a file or a bytesIO object
The function also allows downloading only a single block (of a specified size by using the `block_size` parameter) which can be useful for identifying file type if required. It returns the response headers and the total number of bytes downloaded. 
Tests are updated for the same.
not related - At this point, the unit tests fail due to the set-env command being deprecated.
> Stream downloads

- CHANGELOG.md
- src/zimscraperlib/zim/creator.py
Fixes #69 by not setting filename as `None` in StaticArticle object in `add_binary()`
> Ensure filename in StaticArticle is not None

- tests/download/test_download.py
URL http://google.com/favicon.ico randomly responds with gzip-encoded data
This handles both cases.
> Fixed download test inconsistency

- .pre-commit-config.yaml
- CHANGELOG.md
- src/zimscraperlib/zim/_libkiwix.py
- src/zimscraperlib/zim/archive.py
- tests/zim/conftest.py
- tests/zim/test_archive.py
- tests/zim/test_libkiwix.py
Archive now supports `.counters`, `.article_counter` and `.media_counter`, providing
respectively a parsed dict of the Counter metadata and libkiwix's calculations
for articles and medias.
Implemented as copies of libkiwix code in a private module.
Tests are duplicates of libkiwix's to ensure compatibility
Also adding an ignore rule for flake8. See https://github.com/psf/black/issues/315
> Added ZIM Counter metadata parsing support

- .github/workflows/ci.yml
We should add Python 3.11 tests to CI, since This lib can be run under Python 3.11 now.
> Add Python 3.11 to CI.

- .github/workflows/ci.yml
- CHANGELOG.md
- requirements.txt
- tox.ini
> Update to pylibzim 3.4.0

- pyproject.toml
- src/zimscraperlib/zim/creator.py
- tests/zim/test_zim_creator.py
Fixes #125
Previously, the type annotations of `Creator.config_metadata()` allowed "Tags" to be a list of strings, but didn't handle the conversion to a string, which resulted in python-libzim raising an error.
This commit modifies `Creator.add_metadata()` to accept a list of strings and, if the key of the metadata is "Tags", join them into a single string. A regression test is included. The metadata validation seems have already been written with a tag list in mind (though there is no check that a single tag in such a list should not contain `";"`, not sure if this is intended).
**Note:** the join has been implemented in `Creator.add_metadata`, but the conversion of `datetime.datetime` for the `"Date"` metadata key happens in `python-libzim`. I think splitting the conversion logic …
> Fix handling of tag list in Creator.add_metadata (fix #125)

- CHANGELOG.md
- contrib/README.md
- contrib/encode_video.py
- pyproject.toml
- src/zimscraperlib/video/encoding.py
- src/zimscraperlib/video/presets.py
- tests/video/test_encoding.py
- tests/video/test_video.py
Enabler for https://github.com/openzim/kolibri/issues/75
Fix #123 
- Rework the VideoWebmLow preset for faster encoding and smaller file size (preset has been bumped to version 2)
- target bitrate `-b:v` is reduced to 128k instead of 300k (deemed sufficient)
- `-maxrate` and `-minrate` have been removed (otherwise the quantizer has no room for adaptation)
- `-qmin` is reduced to 18 instead of 30 (significantly reduce the bitrate on very still videos)
- `-qmax` is decreased to 40 instead of 42 
- other settings are left as-is
- When reencoding a video, ffmpeg now uses only 1 CPU thread by default (new arg to `reencode` allows to override this default value)
- New utility to encode a video with an existing preset (for local debugging typically)
https://github.com/openzim/kolibri/issues/75 …
> Fix VP8 low bitrate

- CHANGELOG.md
- README.md
- pyproject.toml
- src/zimscraperlib/filesystem.py
- tests/filesystem/test_filesystem.py
- tests/video/test_video.py
Fix #114 (remaining part is now tracked in #134)
Partial fix of #114, the following test is still failing ; looks like on Alpine setlocale is never raising an error, see issue for details. I don't know if we accept to live with it or add a special detection for Alpine Linux which would skip the test.
```
FAILED tests/i18n/test_i18n.py::test_selocale_unsupported - Failed: DID NOT RAISE <class 'locale.Error'>
```
Some tests were failing on Alpine Linux + `file-magic` is not well maintained / not supporting Alpine Linux
- replace `file-magic` by `python-magic` library, since the last one has support for Alpine + is better maintained
- add installation instruction for Alpine (maybe partial, at least sufficient for tests to pass)
- fix ffprobe test which was failing due to different bitrates …
> Fix alpine tests

- src/zimscraperlib/image/convertion.py
- src/zimscraperlib/image/transformation.py
- src/zimscraperlib/image/utils.py
- src/zimscraperlib/zim/filesystem.py
- src/zimscraperlib/zim/items.py
- tests/image/test_image.py
- tests/zim/test_zim_creator.py
Fix #109
Fix #112 
Type hints were too restrictive / incorrect
- `Item`
- for `**kwargs`, the type specified must be the one of individual param values, not the whole dictionary 
- the `Union[str, bool, bytes]` type hint was replaced by `Any`, because the goal of this param is precisely to pass any type which could be further used
- `FileItem` and `URLItem` were modified as well because they were very close to `StaticItem`
- no change was necessary in `StaticItem` in fact
- references to callback in docstring has been removed because it has been moved to the `add_item` method quite few years ago
- `convert_image`
- `src` and `dst` can be either a `Pathlib.Path` or an `io.BytesIO` (maybe even `typing.BinaryIO` or `typing.IO[bytes]`, but I did not find a convenient way to test this to …
> Fix type hints

- CHANGELOG.md
- src/zimscraperlib/zim/creator.py
- tests/zim/test_zim_creator.py
Fix #119 
- fix CHANGELOG from previous PR #132 ...
- add a `auto_metadata_check` parameter, which default to `True` but can be disabled
One question: I had to disable validation at two places, is it intentional?
> Relax metadata check

- src/zimscraperlib/zim/creator.py
- src/zimscraperlib/zim/items.py
- src/zimscraperlib/zim/providers.py
- tests/zim/conftest.py
- tests/zim/test_zim_creator.py
- libzim `StringProvider` supports both `bytes` and `str` types as `content` but `StaticItem` accepted only `str` in its type hint
- this was detected while migrating `add_item_for` to use new `StaticItem` parameters
- last PR #135 was incorrect 🤦🏻
- using `main` code on kolibri showed an issue when the content passed to `add_item_for`/`StaticItem` is an empty string "" ; content is not set and `StaticItem` fails to know which content provider has to be used 
- accept both `bytes` and `str` types as `content` in `StaticItem`
- accept both `bytes` and `str` types as `content` in scraperlib `StringProvider`
- check at runtime that content type is correct before passing it to the `StringProvider`
- reverse/fix logic of `disable_metadata_checks`
- always set item attributes when passed, even …
> Fix disable_metadata_checks behavior and fix StaticItem support of bytes content

- .pre-commit-config.yaml
- CHANGELOG.md
- pyproject.toml
- src/zimscraperlib/zim/filesystem.py
- Add support for `disable_metadata_checks`, `ignore_duplicates` ~~and `compression`~~ arguments in `make_zim_file` function ("zimwritefs-mode")
- We forgot about this `disable_metadata_checks` when adding this functionality ... while it is the first (and maybe even main) use case ...
- This is a minor fix, but mandatory for migration of TED scraper to Zimscraperlib 3.x
- We should support as well `ignore_duplicates` in `make_zim_file` function ("zimwritefs-mode")
- It will default to `True`, since it most cases this is what we want (we usually do not run a deduplication function before-hand on files stored in the filesystem
- But we could (should ?) do it add replace these duplicates by aliases / redirections
- Relax dependencies versions
- Tests are running fine, this is especially …
> Add arguments to make_zim_file and relax dependencies constraints

- .github/workflows/Tests.yaml
- CHANGELOG.md
- README.md
- pyproject.toml
- tasks.py
- tests/conftest.py
- tests/ogvjs/test_ogvjs.py
Fix #139
Before 3.3, there was a `--runinstalled` switch for tests to disable by default the execution of some tests which were deemed to work only if the package tools were installed.
In 3.3.0, we assumed this switch was not necessary anymore before with new Python bootstrap convention, we are always in installed mode.
This statement was indeed wrong because some persons are building and testing without using our build chain (e.g. they build and test directly from sdist).
This PR adds back the `--runinstalled` switch for tests and corresponding pytest marker to mark tests that are going to work only if package tools are installed.
This PR also implements Python bootstrap 1.0.2 and missing classifiers in Python project
> Add back a runinstalled marker for ogvjs tests

- CHANGELOG.md
- src/zimscraperlib/video/presets.py
- tests/video/test_video.py
Fix #79
`WebmLow` and `WebmHigh` presets are migrated to use VP9 instead of VP8. 
Presets are also enhanced to maximize video quality all while minimizing final file size. A compromise with encoding duration (which is known to be significantly higher with VP9 compared to VP8) is also taken into account (hence the -speed setting values, 0 is optimal but takes too long for minimal quality improvement given our computing power available)
> webm video presets: migrate from VP8 to VP9 for smaller ZIMs

- src/zimscraperlib/zim/filesystem.py
- tests/zim/test_fs.py
> Add utility to validate ZIM folder and filename are OK

- CHANGELOG.md
- src/zimscraperlib/zim/creator.py
- tests/zim/test_zim_creator.py
I can't push on #160 so here's a copy of it with my fixes at the end.
Should it be satisfactory, I suggest we squash all commits into one.
Fixes #155
>  Issue 155: log metadata prior to verification (PR #160 fixes)

- src/zimscraperlib/inputs.py
- src/zimscraperlib/zim/metadata.py
- tests/download/test_download.py
- tests/inputs/test_inputs.py
- tests/zim/test_metadata.py
Fix #164 
Fix #156
Changes:
- New utility function to compute tags from scraper defaults and user provided values
- Also raise error in tags validation when duplicates are found, either in string with semi-colon separator or in 
This does not deduplicate automatically tags, it is still the scraper responsibility to properly pass tags (ideally with the new utility function) since `config_metadata` is more a wrapper passing directly the values as-is, I did not wanted to make an exception for tags
Edit: I had to also modify URL used for yt-dlp tests because former Vimeo URL is now returning a 403 on Github runners. Hopefully the new Jeena Peertube instance will be a little bit more permissive for few years ...
> Enhance tags manipulation

- CHANGELOG.md
- src/zimscraperlib/zim/creator.py
- tests/zim/test_zim_creator.py
Fix #159
Fix https://github.com/openzim/warc2zim/issues/128
- Automatically drop all control characters in metadata except `\r`, `\n` and `\t`
- Automatically strip blank characters ` `, `\r`, `\n` and `\t` in metadata
> Drop disallowed control characters and strip blank characters

- CHANGELOG.md
- README.md
- src/zimscraperlib/i18n.py
Fix #157
- Enhance `locale` setup error message for easier understanding
- Add more information about `locale` requirement in README
> Enhance error when locale fails to setup

- src/zimscraperlib/zim/creator.py
> Fix merge errors of #178 

- CHANGELOG.md
- src/zimscraperlib/i18n.py
- tests/i18n/test_i18n.py
Fix #151 
Changes:
- new `i18n.Lang` class to hold returned values
- `i18n.get_language_details()`, `i18n.get_iso_lang_data()`, `i18n.find_language_names()` and `i18n.update_with_macro` now process / return a new typed `Lang` class
- small fixes around renaming of `i18n.NotFound` to `i18n.NotFoundError` from previous PR (forgot changelog + few wrong docstrings)
> Process / return a new typed Lang class in i18n methods

- pyproject.toml
- src/zimscraperlib/i18n.py
- src/zimscraperlib/zim/archive.py
- src/zimscraperlib/zim/creator.py
- src/zimscraperlib/zim/items.py
- src/zimscraperlib/zim/providers.py
- tests/i18n/test_i18n.py
- tests/zim/test_fs.py
- tests/zim/test_indexing.py
- tests/zim/test_zim_creator.py
CI on main was broken due to a combination of dependencies update:
- a fix on iso639-lang which restored a part2 which was missing and for which we tested the output. I changed the expected output
- a pymupdf update which slightly changed the returned text index of the test PDF for which we tested the exact output. I changed the test to check that index is at least 90% the size of the source.
- a libzim update which introduced proper type hints. I adjusted the usage to match the requirements.
> Fix CI on main

- javascript/package.json
- javascript/yarn.lock
Mandatory due to https://github.com/openzim/python-scraperlib/security/dependabot/2, and never a bad thing especially for small JS like we have here.
> Update JS dependencies

- src/zimscraperlib/rewriting/css.py
- src/zimscraperlib/rewriting/html.py
- src/zimscraperlib/rewriting/js.py
- src/zimscraperlib/rewriting/url_rewriting.py
- tests/rewriting/conftest.py
- tests/rewriting/test_html_rewriting.py
- tests/rewriting/test_js_rewriting.py
- tests/rewriting/test_url_rewriting.py
Changes:
- fix __repr__ of ZimPath / HttpUrl which where too long and not working 
- add support for no pre_head_insert in html rewriter and no js_notify callback in all rewriters
- instead of build `items_to_download` in the rewriter, return complete url rewrite information so that 'users' (e.g. mindtouch scraper) can decide what they want to do
Nota: 
- this has been tested with upcoming changes for mindtouch scraper and is supposed to be feature-complete. In last (and biggest) change, the signature of rewriters are not significantly modified so it is not expected to cause significant changes in warc2zim once we will start https://github.com/openzim/warc2zim/issues/411
> More changes for mindtouch scraper

- src/zimscraperlib/rewriting/html.py
- tests/rewriting/test_html_rewriting.py
For mindtouch scraper, we need to enrich the possibilities of HTML tag rewriting rules, by having access to current base_href and url_rewriter.
> Add access to base_href and url_rewriter in HTML tag rewriting

- src/zimscraperlib/download.py
- src/zimscraperlib/logging.py
Very simplified version of #211 since for now decided not to include an executor but rely on joblib (or another parallel processing lib) for now.
Changes:
- fix few type hints to be more precise
- add standard log format for displaying threads info
> Small changes for mindtouch

- src/zimscraperlib/rewriting/html.py
- tests/rewriting/test_html_rewriting.py
Solution for https://github.com/openzim/warc2zim/issues/421 once warc2zim uses the scraperlib (soon).
Changes:
- do not notify of src rewrite when script src is inline data
> Handle case where JS module is an inline data

- CHANGELOG.md
- src/zimscraperlib/constants.py
- src/zimscraperlib/download.py
- tests/download/test_download.py
We never passed a timeout to these requests call, but obviously we should have (this seems to be the explanation to https://github.com/openzim/mindtouch/issues/80 so far)
> Set default timeout in `download.stream_file` to 10 seconds, and allow to override value

- README.md
> Add ReadTheDocs badge and link

- CHANGELOG.md
- pyproject.toml
- src/zimscraperlib/constants.py
- src/zimscraperlib/filesystem.py
- src/zimscraperlib/image/conversion.py
- src/zimscraperlib/inputs.py
- src/zimscraperlib/typing.py
- src/zimscraperlib/zim/__init__.py
- src/zimscraperlib/zim/_libkiwix.py
- src/zimscraperlib/zim/archive.py
- src/zimscraperlib/zim/creator.py
- src/zimscraperlib/zim/filesystem.py
- src/zimscraperlib/zim/metadata.py
- tests/filesystem/test_filesystem.py
- tests/inputs/test_inputs.py
- tests/zim/conftest.py
- tests/zim/test_fs.py
- tests/zim/test_metadata.py
- tests/zim/test_typing.py
- tests/zim/test_zim_creator.py
Fix https://github.com/openzim/python-scraperlib/issues/205
This is a full rewrite of https://github.com/openzim/python-scraperlib/pull/217, so I've opened a new PR since changes since last review made no more sense from my PoV.
- add types for all metadata, one type per metadata name plus some generic ones for non-standard metadata
- all types are responsible to validate metadata value at initialization time
- validation checks for adherence to the ZIM specification and conventions are automated
- cleanup of unwanted control characters and stripping white characters are **automated in all text metadata**
- whenever possible, try to **automatically clean a "reasonably" bad metadata** (e.g. automaticall accept and remove duplicate tags - harmless - but not duplicate language codes - codes …
> Significantly enhance the safety of metadata manipulation

- src/zimscraperlib/i18n.py
- tests/i18n/test_i18n.py
This PR is preparatory work for #212. 
It is also a rework of #151 / #183 where I obviously was a bit too lazy.
Since this is ready and "significant" and isolated change, I submit it in a dedicated PR.
I've removed two tests which do not really make sense once we use real classes, and are not possible since we cannot init the class with dict values anymore.
CHANGELOG is not updated since anyway we will have to tackle this separately for 5.0.0
This has been tested locally for proper operation with pyright strict mode.
> Move to real classes for i18n classes for proper typing in strict mode

- README.md
> Mention dependency on libcairo in README

- pyproject.toml
Fix #226 
I did not found more direct dependencies than what was listed in the issue.
Remarks:
- for pillow, I confirmed 7.0.0 is ok (tests are green) but last 6.x is not
- for urllib3, 1.26.5 is a minimum for tests to test ; they introduce breaking changes in minor so I restricted to < 2.3 ... to be updated regularly obviously
- for pixexif, I pinned a version like optimize-image did, this is a nightmare otherwise
- for idna, the range is relatively wide open, even if recent versions mention official support of Python 3.12 ... since tests are OK, I feel like it is ok to use an old version if someone needs it
I checked other deps and no update (widening of upper bound) is needed since no newer version exist
> Add missing direct dependencies

- src/zimscraperlib/video/encoding.py
- tests/video/test_video.py
> Allow specifying reencode's tmp dir

- pyproject.toml
Changes:
- add a `py.typed` marker file to indicate that the library is typed (at top-level obviously)
- fix `sdist` configuration (using `include` overrides the whole default logic of sdist content ; we only want to add few more files, which should be done with `artifacts` - just like for the wheel)
Nota: tested succesfully with mindtouch scraper which is now in `strict` type checking mode (on my dev machine, PR ongoing)
> Mark package as typed

- pyproject.toml
Urllib3 2.3.0 is now out, and it is OK with our usage
> Add support for urllib3 2.3.x

- .github/workflows/Publish.yaml
- .github/workflows/Tests.yaml
- .pre-commit-config.yaml
- .readthedocs.yaml
- CHANGELOG.md
- pyproject.toml
- src/zimscraperlib/__about__.py
- src/zimscraperlib/zim/providers.py
- tests/rewriting/conftest.py
Fix #203 
Nota:
- I had to disable a new ruff/flake rule, this is tracked separately as https://github.com/openzim/python-scraperlib/issues/246 because should we decide to fix this, it will need a major release
- I had to keep pyright at 1.1.391, 1.1.392 (even 1.1.392.post0) was giving what looks like false positives
> Upgrade to Python 3.13

- .pre-commit-config.yaml
- CHANGELOG.md
- javascript/package.json
- javascript/yarn.lock
- openzim.toml
- pyproject.toml
- src/zimscraperlib/filesystem.py
- src/zimscraperlib/fix_ogvjs_dist.py
- src/zimscraperlib/html.py
- src/zimscraperlib/image/optimization.py
- src/zimscraperlib/misc.py
- src/zimscraperlib/rewriting/css.py
- src/zimscraperlib/rewriting/html.py
- src/zimscraperlib/rewriting/js.py
- src/zimscraperlib/rewriting/url_rewriting.py
- src/zimscraperlib/types.py
- src/zimscraperlib/uri.py
- src/zimscraperlib/zim/__init__.py
- src/zimscraperlib/zim/_libkiwix.py
- src/zimscraperlib/zim/archive.py
- src/zimscraperlib/zim/creator.py
- src/zimscraperlib/zim/filesystem.py
- src/zimscraperlib/zim/indexing.py
- src/zimscraperlib/zim/items.py
- src/zimscraperlib/zim/providers.py
- tests/rewriting/test_js_rewriting.py
- tests/zim/test_metadata.py
Fix #249
Remark: I checked the impact of Markdown modification on few cases and it looks like there is no impact (what was broken is still broken, what was ok is still ok)
> Upgrade to wombat 3.8.8 and other Python/JS dependencies

- CHANGELOG.md
- src/zimscraperlib/rewriting/js.py
- tests/rewriting/test_js_rewriting.py
Fix #255
For some reason, we were missing one JS rewriting rule implemented in wabac: https://github.com/webrecorder/wabac.js/blame/364b6e2d329f5ff92d680b482ec4f7e2036d6603/src/rewrite/jsrewriter.ts#L181
This has been put into wabac.js at https://github.com/webrecorder/wabac.js/pull/164 ; looks like we missed the opportunity to back-port this into our rewriting code. Most probably because we only focus on fuzzy rules and forgot to also consider these JS rewriting rules. I've updated the release checklist to also check this file.
I've also checked all other rules in this file and realized that we missed some other changes, not linked to this bug but still worth to include, so they are in a distinct commit.
To be merged after https://github.com/openzim/python-scraperlib/pull/257
> Add JS rewriting rule to ignore import function rewriting

- CHANGELOG.md
- pyproject.toml
- src/zimscraperlib/zim/dedup.py
- tests/zim/test_dedup.py
Fix #33 
Note that this is kinda a resurrection of https://github.com/openzim/python-scraperlib/pull/86 where important things have already been discussed (e.g. the fact that we do not want to extend the Creator API but add a new distinct API to better trace memory issues)
> Add utility to deduplicate ZIM items and replace them with redirects at ZIM creation time

- .pre-commit-config.yaml
- CHANGELOG.md
- openzim.toml
- pyproject.toml
- src/zimscraperlib/image/conversion.py
Upgraded dependencies, and especially widen the `beartype` allowed range of versions to fetch latest one.
> Upgrade dependencies
